# See: https://github.com/actions-rs/example/blob/master/.github/workflows/nightly_lints.yml
---
on:
  push:
    branches:
      - master
      - develop
  pull_request:

name: Lints
jobs:
  fmt:
    name: rustfmt
    runs-on: [self-hosted, light]
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2
      - name: Install cargo-make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --debug cargo-make
      - name: Run cargo fmt
        run: cargo make fmt-check
  clippy:
    name: Clippy
    runs-on: [self-hosted, heavy]
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2
      - name: Install cargo-make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --debug cargo-make
      - run: cargo make build-contracts
      - name: Run Contract cargo clippy
        run: cargo make clippy
      - name: Run cargo clippy
        run: cargo clippy

  contracts:
    name: eth-contracts
    runs-on: [self-hosted, light]
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2
      - name: Install cargo-make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --debug cargo-make
      - name: Run yarn lint
        run: cargo make yarn-check
